"""trades stop_loss_order_id para orden real de stop-loss

Revision ID: 582084654a38
Revises: 417dd0527945
Create Date: 2026-08-31 05:55:22.906001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582084654a38'
down_revision: Union[str, None] = '417dd0527945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('stop_loss_order_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'stop_loss_order_id')
    # ### end Alembic commands ###
