"""baseline: esquema actual

Revision ID: c14d22a7cf9b
Revises: 
Create Date: 2026-08-28 11:36:26.078244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import SQLAlchemyError


# revision identifiers, used by Alembic.
revision: str = 'c14d22a7cf9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_candles_symbol'), 'price_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_candles_timestamp'), 'price_candles', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('fast', sa.Integer(), nullable=False),
    sa.Column('slow', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('max_candles', sa.Integer(), nullable=True),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=True),
    sa.Column('trend_filter_enabled', sa.Boolean(), nullable=True),
    sa.Column('trend_sma_period', sa.Integer(), nullable=True),
    sa.Column('trend_require_rising', sa.Boolean(), nullable=True),
    sa.Column('candles_count', sa.Integer(), nullable=True),
    sa.Column('candle_start', sa.DateTime(), nullable=True),
    sa.Column('candle_end', sa.DateTime(), nullable=True),
    sa.Column('final_equity', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('buy_and_hold_pnl_pct', sa.Float(), nullable=True),
    sa.Column('alpha_pct', sa.Float(), nullable=True),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_created_at'), 'backtest_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_runs_symbol'), 'backtest_runs', ['symbol'], unique=False)
    op.create_index(op.f('ix_backtest_runs_timeframe'), 'backtest_runs', ['timeframe'], unique=False)
    op.create_index(op.f('ix_backtest_runs_user_id'), 'backtest_runs', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('max_position_pct', sa.Float(), nullable=True),
    sa.Column('stop_loss_pct', sa.Float(), nullable=True),
    sa.Column('take_profit_pct', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('binance_api_key_enc', sa.Text(), nullable=False),
    sa.Column('binance_secret_key_enc', sa.Text(), nullable=False),
    sa.Column('testnet', sa.Boolean(), nullable=True),
    sa.Column('paper_trading', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'PAUSED', 'STOPPED', name='botstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('signal', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('indicators', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_runs_created_at'), 'strategy_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_runs_strategy_id'), 'strategy_runs', ['strategy_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FILLED', 'CANCELED', 'FAILED', name='orderstatus'), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_opened_at'), 'trades', ['opened_at'], unique=False)
    # ### end Alembic commands ###

    _setup_timescaledb()


def _setup_timescaledb() -> None:
    """Best-effort TimescaleDB setup for price_candles — mirrors what
    app/db/database.py used to do at app startup before Alembic existed.
    Wrapped in its own savepoint so that plain PostgreSQL (no timescaledb
    extension available, e.g. local dev) doesn't abort the rest of this
    migration — it just continues without hypertable/retention support."""
    bind = op.get_bind()
    bind.execute(sa.text("SAVEPOINT timescaledb_setup"))
    try:
        bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS timescaledb"))
        bind.execute(sa.text(
            "SELECT create_hypertable('price_candles', 'timestamp', if_not_exists => TRUE)"
        ))
        bind.execute(sa.text(
            "SELECT add_retention_policy('price_candles', INTERVAL '90 days', if_not_exists => TRUE)"
        ))
        bind.execute(sa.text("RELEASE SAVEPOINT timescaledb_setup"))
    except SQLAlchemyError:
        bind.execute(sa.text("ROLLBACK TO SAVEPOINT timescaledb_setup"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_opened_at'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_strategy_runs_strategy_id'), table_name='strategy_runs')
    op.drop_index(op.f('ix_strategy_runs_created_at'), table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_table('bot_configs')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_backtest_runs_user_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_timeframe'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_symbol'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_created_at'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_price_candles_timestamp'), table_name='price_candles')
    op.drop_index(op.f('ix_price_candles_symbol'), table_name='price_candles')
    op.drop_table('price_candles')
    # ### end Alembic commands ###
